[workspace]
resolver = "2"
members = [
    "unwrap_check",
    "mpsc_blocking_send",
    "large_futures",
    "index_access_check",
    "tokio_time_interval",
    "instant"
]

[workspace.dependencies]
dylint_linting = "4.1.0"
dylint_testing = "4.1.0"
